error in script scripts/proxy_interceptor1.py
Traceback (most recent call last):                                                                                                                                                                                                         
  File "scripts/proxy_interceptor1.py", line 16, in <module>                                                                                                                                                                               
    kmeans_model = pd.read_pickle(model_file)                                                                                                                                                                                              
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                              
  File "/usr/lib/python3/dist-packages/pandas/io/pickle.py", line 190, in read_pickle                                                                                                                                                      
    with get_handle(                                                                                                                                                                                                                       
         ^^^^^^^^^^^                                                                                                                                                                                                                       
  File "/usr/lib/python3/dist-packages/pandas/io/common.py", line 865, in get_handle                                                                                                                                                       
    handle = open(handle, ioargs.mode)                                                                                                                                                                                                     
             ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                     
FileNotFoundError: [Errno 2] No such file or directory: 'kmeans_model.sav' 
